[versions]
assertk = "0.28.1"
kotlin = "2.2.21"
kotlinCoroutines = "1.10.2"
junitBom = "6.0.1"
sobergAocApi = "1.0"

[libraries]
# Kotlin
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }

# Third-party
soberg-aoc-api = { module = "com.github.jsoberg:Kotlin-AoC-API", version.ref = "sobergAocApi" }

# Test
test-assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }
test-kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }

# Test - JUnit
test-junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junitBom" }
test-junitJupiter = { module = "org.junit.jupiter:junit-jupiter" }
test-junitJupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }
test-junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }